version : '3'
services:
  bff:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: marketplace.gcr.io/google/mongodb4
    ports:
      - '27017:27017'
